# Generated by Django 4.2.3 on 2023-08-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apptutor', '0002_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
    ]
